name: Cpp
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test yivo
        run: |
          cd cpp
          mkdir -p build
          cd build
          cmake ..
          make
          ./gtests/main-gtest